<a href="https://colab.research.google.com/github/24mca00py0033-gif/Ai-ml-dl-nlp/blob/main/ColoumnTransformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [5]:
df=pd.read_csv('covid_toy.csv')

In [6]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [11]:
X_train

    age  gender  fever   cough       city
28   16    Male  104.0    Mild    Kolkata
31   83    Male  103.0    Mild    Kolkata
50   19    Male  101.0    Mild      Delhi
64   42    Male  104.0    Mild     Mumbai
12   25  Female   99.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
53   83    Male   98.0    Mild      Delhi
90   59  Female   99.0  Strong      Delhi
32   34  Female  101.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata

[80 rows x 5 columns]

In [14]:
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])

In [15]:
X_test_fiver=si.fit_transform(X_test[['fever']])

In [16]:
X_train_fever.shape

(80, 1)

In [18]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [19]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [21]:
from sklearn.compose import ColumnTransformer

In [22]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
])

In [23]:
transformer.fit_transform(X_train).shape

(80, 6)

In [24]:
transformer.transform(X_test).shape

(20, 6)