<a href="https://colab.research.google.com/github/24mca00py0033-gif/Ai-ml-dl-nlp/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('cars.csv')

In [ ]:
df.sample(10)

           brand  km_driven    fuel                 owner  selling_price
1683  Volkswagen      17000  Petrol           First Owner         678000
394       Toyota     240000  Diesel           Third Owner         250000
5514       Skoda      31000  Diesel           First Owner         860000
2135        Audi      70000  Diesel           First Owner        1850000
4176  Volkswagen      80000  Diesel  Fourth & Above Owner         250000
1958       Honda      28000  Petrol           First Owner         860000
6735       Honda      97000  Petrol          Second Owner         250000
5815      Maruti      16000     CNG           First Owner         370000
2367    Mahindra     120000  Diesel           First Owner         450000
5027    Mahindra     121779  Diesel           First Owner         532000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [ ]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [ ]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [ ]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new=ohe.transform(X_test[['fuel','owner']]).toarray()

In [ ]:
X_train

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner
...        ...        ...     ...           ...
3606      Ford      35000  Diesel   First Owner
5704    Maruti     120000  Petrol   First Owner
6637      Tata      15000  Petrol   First Owner
2575    Maruti      32500  Diesel  Second Owner
7336     Isuzu     121000  Diesel   First Owner

[6502 rows x 4 columns]

In [ ]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Jeep', 60000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 25000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Tata', 15000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 32500, 0.0, ..., 1.0, 0.0, 0.0],
       ['Isuzu', 121000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [ ]:
counts = df['brand'].value_counts()

In [ ]:
df['brand'].nunique()
threshold = 100

In [ ]:
repl = counts[counts <= threshold].index

In [ ]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
446,False,False,True,False,False,False,False,False,False,False,False,False,False
589,False,True,False,False,False,False,False,False,False,False,False,False,False
6261,False,False,False,False,True,False,False,False,False,False,False,False,False
6750,False,False,True,False,False,False,False,False,False,False,False,False,False
6285,False,False,False,False,False,False,True,False,False,False,False,False,False