<a href="https://colab.research.google.com/github/24mca00py0033-gif/Ai-ml-dl-nlp/blob/main/OrdinalandLableEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('customer.csv')

In [4]:
df.sample(5)

    age  gender   review education purchased
44   77  Female  Average        UG        No
15   75    Male     Poor        UG        No
42   30  Female     Good        PG       Yes
35   74    Male     Poor    School       Yes
29   83  Female  Average        UG       Yes

In [6]:
df=df.iloc[:,2:]

In [7]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [11]:
X_train

     review education
36     Good        UG
19     Poor        PG
20  Average    School
39     Poor        PG
16     Poor        UG
31     Poor    School
34  Average    School
23     Good    School
6      Good    School
3      Good        PG
49     Good        UG
40     Good    School
0   Average    School
21  Average        PG
37  Average        PG
33     Good        PG
1      Poor        UG
13  Average    School
47     Good        PG
38     Good    School
41     Good        PG
14     Poor        PG
29  Average        UG
27     Poor        PG
11     Good        UG
7      Poor    School
48     Good        UG
44  Average        UG
22     Poor        PG
18     Good    School
30  Average        UG
12     Poor    School
17     Poor        UG
25     Good    School
26     Poor        PG
8   Average        UG
43     Poor        PG
10     Good        UG
32  Average        UG
35     Poor    School

In [12]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)
X_train=oe.transform(X_train)

In [13]:
X_train

array([[2., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [1., 2.],
       [1., 2.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 0.]])

In [14]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(y_train)
y_train=le.transform(y_train)

In [16]:
le.classes_

array(['No', 'Yes'], dtype=object)